# Generated by Django 4.1 on 2022-08-14 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rword', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RBoardLikeUsers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'rboard_like_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_content', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='RBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField(verbose_name='문장')),
                ('s_contents', models.TextField(verbose_name='문장 설명')),
                ('write_dttm', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('like_users', models.ManyToManyField(blank=True, related_name='like_rborads', to=settings.AUTH_USER_MODEL)),
                ('word_tag', models.ManyToManyField(related_name='word_tag', to='rword.tag')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '문장게시판',
                'verbose_name_plural': '문장게시판',
                'db_table': 'rboard',
            },
        ),
    ]
