# Generated by Django 4.1 on 2022-08-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rword', '0002_rboardlikeusers_tag_rboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rboard',
            name='s_contents',
            field=models.TextField(verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='rboard',
            name='sentence',
            field=models.CharField(max_length=300, verbose_name='문장'),
        ),
    ]
