# Generated by Django 4.1 on 2022-08-15 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rword", "0005_remove_rboard_like_users_remove_rboard_s_keyword_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SentenceList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sentence", models.CharField(max_length=100, verbose_name="문장")),
            ],
            options={"db_table": "rwordsent",},
        ),
    ]
