# Generated by Django 4.1 on 2022-08-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rword', '0007_sentencelist_write_dttm_sentencelist_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentencelist',
            name='contents',
            field=models.TextField(null=True, verbose_name='설명'),
        ),
    ]
