# Generated by Django 4.1 on 2022-08-18 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rword', '0009_sentencelistcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentencelist',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_sentence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SBoardLikeUsers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rword.sentencelist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
