# Generated by Django 4.1 on 2022-08-18 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rword', '0010_sentencelist_like_users_sboardlikeusers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sboardlikeusers',
            options={'managed': False},
        ),
    ]
