# Generated by Django 4.1 on 2022-08-18 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rword', '0011_alter_sboardlikeusers_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sboardlikeusers',
            table='rwordsent_like_users',
        ),
    ]
