# Generated by Django 4.1 on 2022-08-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rword', '0012_alter_sboardlikeusers_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentencelist',
            name='hits',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
    ]
