# Generated by Django 4.1 on 2022-08-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rword', '0013_sentencelist_hits'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentenceLikeUsers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'rwordsent_like_users',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='SBoardLikeUsers',
        ),
    ]
