# Generated by Django 4.1 on 2022-08-07 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='글 제목')),
                ('contents', models.TextField(verbose_name='글 내용')),
                ('writer', models.CharField(max_length=32, verbose_name='작성자')),
                ('write_dttm', models.DateTimeField(auto_now_add=True, verbose_name='글 작성일')),
                ('board_name', models.CharField(default='일반인', max_length=32, verbose_name='게시판 종류')),
                ('update_dttm', models.DateTimeField(auto_now=True, verbose_name='최종 수정일')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='조회수')),
            ],
            options={
                'verbose_name': '게시판',
                'verbose_name_plural': '게시판',
                'db_table': 'board',
            },
        ),
    ]
