# Generated by Django 4.1 on 2022-08-19 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rword", "0014_sentencelikeusers_delete_sboardlikeusers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardLikeUsers",
            fields=[("id", models.BigAutoField(primary_key=True, serialize=False)),],
            options={"db_table": "board_like_users", "managed": False,},
        ),
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64, verbose_name="글 제목")),
                ("contents", models.TextField(verbose_name="글 내용")),
                (
                    "write_dttm",
                    models.DateTimeField(auto_now_add=True, verbose_name="글 작성일"),
                ),
                (
                    "board_name",
                    models.CharField(
                        default="Public", max_length=32, verbose_name="게시판 종류"
                    ),
                ),
                (
                    "update_dttm",
                    models.DateTimeField(auto_now=True, verbose_name="최종 수정일"),
                ),
                ("hits", models.PositiveIntegerField(default=0, verbose_name="조회수")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="Images/",
                        verbose_name="썸네일 이미지",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="Files", verbose_name="첨부 파일"
                    ),
                ),
                (
                    "like_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="like_borads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sentence",
                    models.ForeignKey(
                        default="",
                        max_length=64,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="rword.sentencelist",
                        verbose_name="문장",
                    ),
                ),
                (
                    "writer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "게시판",
                "verbose_name_plural": "게시판",
                "db_table": "board",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="board.board"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
