# Generated by Django 4.1 on 2022-08-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='sentence',
            field=models.CharField(default='', max_length=64, verbose_name='문장'),
        ),
    ]
