# Generated by Django 4.1 on 2022-08-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_board_sentence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='board_name',
            field=models.CharField(default='Public', max_length=32, verbose_name='게시판 종류'),
        ),
    ]
