# Generated by Django 4.1 on 2022-08-18 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rword', '0013_sentencelist_hits'),
        ('board', '0002_alter_board_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='sentence',
            field=models.ForeignKey(default='', max_length=64, on_delete=django.db.models.deletion.DO_NOTHING, to='rword.sentencelist', verbose_name='문장'),
        ),
    ]
