# Generated by Django 4.1 on 2022-08-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_alter_board_file_alter_board_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='image',
            field=models.ImageField(null=True, upload_to='Images/', verbose_name='썸네일 이미지'),
        ),
    ]
