# Generated by Django 4.1 on 2022-08-10 08:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0008_alter_board_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardLikeUsers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'board_like_users',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='board',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_borads', to=settings.AUTH_USER_MODEL),
        ),
    ]
