# Generated by Django 4.1 on 2022-08-10 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_boardlikeusers_board_like_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFILE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadfile', models.FileField(blank=True, null=True, upload_to='Files')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board')),
            ],
        ),
    ]
