# Generated by Django 4.1 on 2022-08-10 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_uploadfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadFILE',
        ),
    ]
