# Generated by Django 4.1 on 2022-08-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_delete_uploadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='image',
            field=models.ImageField(null=True, upload_to='Images/', verbose_name='썸네일 이미지'),
        ),
    ]
