# Generated by Django 4.1 on 2022-08-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_alter_board_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Images/', verbose_name='썸네일 이미지'),
        ),
    ]
